server:
  port: 8888
spring:
  application:
    name: config-server
#LOCAL    
#  profiles:
#    active:
#    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guimaraes/guimaraes-ms-config-server-repository.git
#PRIVATE
#          uri: https://github.com/guimaraes/guimaraes-ms-repository-private.git
#          username: 
#          password: 
          default-label: main
          search-paths:
          - 'greeting-service*'